/**
 * Discord Bot Profile Updater
 *
 * Applies the entity's identity (name + avatar) to a Discord bot
 * via the Discord REST API. No discord.js dependency — raw HTTP.
 *
 * This module is Discord-specific (adapter layer).
 * The avatar image and name are generated by the engine layer.
 */

import { request } from "node:https";

const DISCORD_API = "discord.com";
const DISCORD_API_PATH = "/api/v10/users/@me";

export interface BotProfileUpdate {
  username: string;
  avatarPng: Buffer;
}

export interface BotProfileResult {
  success: boolean;
  username?: string;
  error?: string;
}

/**
 * Update the Discord bot's username and avatar.
 *
 * @param botToken - Discord bot token
 * @param profile - New username and avatar PNG buffer
 */
export async function updateDiscordBotProfile(
  botToken: string,
  profile: BotProfileUpdate,
): Promise<BotProfileResult> {
  const avatarBase64 = `data:image/png;base64,${profile.avatarPng.toString("base64")}`;

  const body = JSON.stringify({
    username: profile.username,
    avatar: avatarBase64,
  });

  return new Promise((resolve) => {
    const req = request(
      {
        hostname: DISCORD_API,
        path: DISCORD_API_PATH,
        method: "PATCH",
        headers: {
          Authorization: `Bot ${botToken}`,
          "Content-Type": "application/json",
          "Content-Length": Buffer.byteLength(body),
        },
      },
      (res) => {
        let data = "";
        res.on("data", (chunk: string) => (data += chunk));
        res.on("end", () => {
          if (res.statusCode === 200) {
            try {
              const parsed = JSON.parse(data);
              resolve({
                success: true,
                username: parsed.username,
              });
            } catch {
              resolve({ success: true, username: profile.username });
            }
          } else if (res.statusCode === 429) {
            // Rate limited
            resolve({
              success: false,
              error: `Rate limited by Discord. Try again later.`,
            });
          } else {
            resolve({
              success: false,
              error: `Discord API returned ${res.statusCode}: ${data}`,
            });
          }
        });
      },
    );

    req.on("error", (err) => {
      resolve({ success: false, error: err.message });
    });

    req.write(body);
    req.end();
  });
}
