/**
 * Sound Parameter Generation Tests
 *
 * Tests the sound expression parameters generated by the expression adapter.
 * Sound parameters drive the dashboard's Web Audio API procedural generation.
 * These tests verify the computation logic that determines pitch, tempo, volume,
 * wobble, waveform, pattern/cry balance, and complexity from entity state.
 *
 * The generateSoundParams function is private, so all tests go through
 * the public generateExpressionParams API and inspect the .sound output.
 */

import { describe, it, expect } from "vitest";
import { generateExpressionParams } from "../../src/expression/expression-adapter.js";
import { createFixedSeed } from "../../src/genesis/seed-generator.js";
import type {
  Status,
  PerceptionMode,
  HardwareBody,
  SubTraits,
} from "../../src/types.js";
import type { SulkState, SulkSeverity } from "../../src/mood/sulk-engine.js";

// --- Test helpers ---

const HW: HardwareBody = {
  platform: "darwin",
  arch: "arm64",
  totalMemoryGB: 16,
  cpuModel: "Test CPU",
  storageGB: 256,
};

function makeStatus(overrides: Partial<Status> = {}): Status {
  return {
    mood: 50,
    energy: 50,
    curiosity: 50,
    comfort: 50,
    languageLevel: 0,
    perceptionLevel: 0,
    growthDay: 0,
    lastInteraction: "never",
    ...overrides,
  };
}

const NO_SULK: SulkState = {
  isSulking: false,
  severity: "none",
  recoveryInteractions: 0,
  sulkingSince: null,
};

function makeSulk(severity: SulkSeverity): SulkState {
  return {
    isSulking: severity !== "none",
    severity,
    recoveryInteractions: 0,
    sulkingSince: severity !== "none" ? "2026-02-19T10:00:00Z" : null,
  };
}

function makeTraits(overrides: Partial<SubTraits> = {}): SubTraits {
  return {
    sensitivity: 50,
    sociability: 50,
    rhythmAffinity: 50,
    memoryDepth: 50,
    expressiveness: 50,
    ...overrides,
  };
}

function makeSeed(
  species: PerceptionMode = "chromatic",
  traits?: Partial<SubTraits>,
) {
  return createFixedSeed({
    perception: species,
    hardwareBody: HW,
    subTraits: traits ? makeTraits(traits) : undefined,
  });
}

/** Helper: extract just the sound params for a given configuration. */
function soundParams(
  species: PerceptionMode,
  status: Partial<Status> = {},
  growthDay = 30,
  traits?: Partial<SubTraits>,
  sulk: SulkState = NO_SULK,
) {
  const seed = makeSeed(species, traits);
  return generateExpressionParams(seed, makeStatus(status), 0, growthDay, sulk)
    .sound;
}

const ALL_SPECIES: PerceptionMode[] = [
  "chromatic",
  "vibration",
  "geometric",
  "thermal",
  "temporal",
  "chemical",
];

// =====================================================================
// 1. Pitch: mood -> frequency mapping with species base pitch
// =====================================================================

describe("sound params -- pitch", () => {
  it("pitch increases monotonically with mood", () => {
    const pitches = [0, 25, 50, 75, 100].map(
      (mood) => soundParams("chromatic", { mood }).pitch,
    );
    for (let i = 1; i < pitches.length; i++) {
      expect(pitches[i]).toBeGreaterThan(pitches[i - 1]);
    }
  });

  it("all species stay within 80-800 Hz at extreme moods", () => {
    for (const species of ALL_SPECIES) {
      const low = soundParams(species, { mood: 0 });
      const high = soundParams(species, { mood: 100 });
      expect(low.pitch).toBeGreaterThanOrEqual(80);
      expect(high.pitch).toBeLessThanOrEqual(800);
    }
  });

  it("thermal has distinctly lower pitch than chromatic (basePitch 165 vs 440)", () => {
    const thermal = soundParams("thermal", { mood: 50 });
    const chromatic = soundParams("chromatic", { mood: 50 });
    expect(chromatic.pitch - thermal.pitch).toBeGreaterThan(200);
  });

  it("pitch is always a rounded integer", () => {
    for (const mood of [0, 33, 67, 100]) {
      const params = soundParams("chemical", { mood });
      expect(Number.isInteger(params.pitch)).toBe(true);
    }
  });
});

// =====================================================================
// 2. Tempo: energy -> BPM mapping with species base tempo
// =====================================================================

describe("sound params -- tempo", () => {
  it("tempo increases with energy", () => {
    const tempos = [0, 50, 100].map(
      (energy) => soundParams("vibration", { energy }).tempo,
    );
    for (let i = 1; i < tempos.length; i++) {
      expect(tempos[i]).toBeGreaterThan(tempos[i - 1]);
    }
  });

  it("tempo stays within 30-200 BPM for all species at energy extremes", () => {
    for (const species of ALL_SPECIES) {
      expect(soundParams(species, { energy: 0 }).tempo).toBeGreaterThanOrEqual(30);
      expect(soundParams(species, { energy: 100 }).tempo).toBeLessThanOrEqual(200);
    }
  });

  it("vibration is fastest and thermal is slowest at neutral energy", () => {
    const vib = soundParams("vibration", { energy: 50 });
    const therm = soundParams("thermal", { energy: 50 });
    for (const species of ALL_SPECIES) {
      const sp = soundParams(species, { energy: 50 });
      expect(vib.tempo).toBeGreaterThanOrEqual(sp.tempo);
      expect(therm.tempo).toBeLessThanOrEqual(sp.tempo);
    }
  });

  it("tempo is always a rounded integer", () => {
    for (const energy of [0, 33, 67, 100]) {
      expect(Number.isInteger(soundParams("temporal", { energy }).tempo)).toBe(true);
    }
  });
});

// =====================================================================
// 3. Volume: energy + expressiveness trait
// =====================================================================

describe("sound params -- volume", () => {
  it("volume increases with energy and has a floor above 0 at zero energy", () => {
    const low = soundParams("chromatic", { energy: 0 });
    const high = soundParams("chromatic", { energy: 100 });
    expect(high.volume).toBeGreaterThan(low.volume);
    expect(low.volume).toBeGreaterThan(0);
  });

  it("high expressiveness amplifies volume", () => {
    const lowExpr = soundParams("chromatic", { energy: 70 }, 30, { expressiveness: 10 });
    const highExpr = soundParams("chromatic", { energy: 70 }, 30, { expressiveness: 90 });
    expect(highExpr.volume).toBeGreaterThan(lowExpr.volume);
  });

  it("volume stays in 0-1 for all species and extreme inputs", () => {
    for (const species of ALL_SPECIES) {
      for (const energy of [0, 100]) {
        for (const expr of [0, 100]) {
          const v = soundParams(species, { energy }, 30, { expressiveness: expr }).volume;
          expect(v).toBeGreaterThanOrEqual(0);
          expect(v).toBeLessThanOrEqual(1);
        }
      }
    }
  });
});

// =====================================================================
// 4. Wobble: inverse comfort + sensitivity trait
// =====================================================================

describe("sound params -- wobble", () => {
  it("wobble increases as comfort decreases (inverse relationship)", () => {
    expect(soundParams("chromatic", { comfort: 10 }).wobble)
      .toBeGreaterThan(soundParams("chromatic", { comfort: 90 }).wobble);
  });

  it("high sensitivity amplifies wobble", () => {
    const lowSens = soundParams("chromatic", { comfort: 30 }, 30, { sensitivity: 10 });
    const highSens = soundParams("chromatic", { comfort: 30 }, 30, { sensitivity: 90 });
    expect(highSens.wobble).toBeGreaterThan(lowSens.wobble);
  });

  it("geometric has lowest wobble and chemical has highest at neutral comfort", () => {
    const geo = soundParams("geometric", { comfort: 50 });
    const chem = soundParams("chemical", { comfort: 50 });
    for (const species of ALL_SPECIES) {
      const sp = soundParams(species, { comfort: 50 });
      expect(geo.wobble).toBeLessThanOrEqual(sp.wobble);
      expect(chem.wobble).toBeGreaterThanOrEqual(sp.wobble);
    }
  });

  it("wobble stays in 0-1 at all comfort and sensitivity extremes", () => {
    for (const species of ALL_SPECIES) {
      for (const comfort of [0, 100]) {
        for (const sens of [0, 100]) {
          const w = soundParams(species, { comfort }, 30, { sensitivity: sens }).wobble;
          expect(w).toBeGreaterThanOrEqual(0);
          expect(w).toBeLessThanOrEqual(1);
        }
      }
    }
  });
});

// =====================================================================
// 5. Complexity: sqrt growth curve over time
// =====================================================================

describe("sound params -- complexity growth curve", () => {
  it("matches the formula: min(1, 0.1 + sqrt(day/120) * 0.9) at key milestones", () => {
    expect(soundParams("chromatic", {}, 0).complexity).toBeCloseTo(0.1, 5);
    expect(soundParams("chromatic", {}, 30).complexity).toBeCloseTo(0.55, 1);
    expect(soundParams("chromatic", {}, 120).complexity).toBeCloseTo(1.0, 5);
  });

  it("increases monotonically and caps at 1.0 beyond day 120", () => {
    const days = [0, 1, 7, 14, 30, 60, 90, 120, 365];
    let prev = -1;
    for (const day of days) {
      const c = soundParams("chromatic", {}, day).complexity;
      expect(c).toBeGreaterThanOrEqual(prev);
      prev = c;
    }
    expect(soundParams("chromatic", {}, 365).complexity).toBe(1.0);
  });

  it("is species-independent (depends only on growthDay)", () => {
    for (const day of [0, 60, 120]) {
      const values = ALL_SPECIES.map((sp) => soundParams(sp, {}, day).complexity);
      for (let i = 1; i < values.length; i++) {
        expect(values[i]).toBeCloseTo(values[0], 5);
      }
    }
  });
});

// =====================================================================
// 6. Pattern vs cry balance
// =====================================================================

describe("sound params -- pattern/cry balance", () => {
  it("chromatic is cry-dominant, vibration and geometric are pattern-dominant", () => {
    const chr = soundParams("chromatic");
    const vib = soundParams("vibration");
    const geo = soundParams("geometric");
    expect(chr.cryWeight).toBeGreaterThan(chr.patternWeight);
    expect(vib.patternWeight).toBeGreaterThan(vib.cryWeight);
    expect(geo.patternWeight).toBeGreaterThan(geo.cryWeight);
    expect(geo.patternWeight).toBeGreaterThan(0.7);
  });

  it("high expressiveness increases cry weight", () => {
    const lowExpr = soundParams("vibration", {}, 30, { expressiveness: 10 });
    const highExpr = soundParams("vibration", {}, 30, { expressiveness: 90 });
    expect(highExpr.cryWeight).toBeGreaterThan(lowExpr.cryWeight);
  });

  it("maturity shifts balance toward more patterns over 300 days", () => {
    const young = soundParams("chromatic", {}, 0, { expressiveness: 50 });
    const mature = soundParams("chromatic", {}, 300, { expressiveness: 50 });
    expect(mature.patternWeight).toBeGreaterThanOrEqual(young.patternWeight);
  });
});

// =====================================================================
// 7. Species waveform assignments
// =====================================================================

describe("sound params -- species waveforms", () => {
  it("each species maps to its designated waveform", () => {
    const expected: Record<PerceptionMode, string> = {
      chromatic: "sine",
      vibration: "square",
      geometric: "triangle",
      thermal: "sine",
      temporal: "triangle",
      chemical: "sawtooth",
    };
    for (const [species, waveform] of Object.entries(expected)) {
      expect(soundParams(species as PerceptionMode).waveform).toBe(waveform);
    }
  });
});

// =====================================================================
// 8. Sulk suppression
// =====================================================================

describe("sound params -- sulk suppression", () => {
  it("severe sulk fixes pitch=150, tempo=40, complexity=0.05, near-zero volume", () => {
    const params = soundParams("chromatic", {}, 30, undefined, makeSulk("severe"));
    expect(params.pitch).toBe(150);
    expect(params.tempo).toBe(40);
    expect(params.complexity).toBe(0.05);
    expect(params.volume).toBeLessThan(0.02);
  });

  it("sulk pitch and tempo ignore entity mood and energy", () => {
    const happy = soundParams("chromatic", { mood: 100, energy: 100 }, 30, undefined, makeSulk("severe"));
    const sad = soundParams("chromatic", { mood: 0, energy: 0 }, 30, undefined, makeSulk("severe"));
    expect(happy.pitch).toBe(sad.pitch);
    expect(happy.tempo).toBe(sad.tempo);
  });

  it("sulk complexity is fixed regardless of growth day", () => {
    expect(soundParams("chromatic", {}, 0, undefined, makeSulk("moderate")).complexity).toBe(0.05);
    expect(soundParams("chromatic", {}, 365, undefined, makeSulk("moderate")).complexity).toBe(0.05);
  });

  it("sulk preserves species waveform", () => {
    for (const species of ALL_SPECIES) {
      const normal = soundParams(species);
      const sulking = soundParams(species, {}, 30, undefined, makeSulk("severe"));
      expect(sulking.waveform).toBe(normal.waveform);
    }
  });
});

// =====================================================================
// 9. Cross-species sound differentiation
// =====================================================================

describe("sound params -- cross-species differentiation", () => {
  it("no two species produce identical sound profiles at neutral status", () => {
    const results = ALL_SPECIES.map((sp) => soundParams(sp));
    for (let i = 0; i < results.length; i++) {
      for (let j = i + 1; j < results.length; j++) {
        const a = results[i];
        const b = results[j];
        const differ =
          a.pitch !== b.pitch ||
          a.tempo !== b.tempo ||
          a.waveform !== b.waveform ||
          Math.abs(a.wobble - b.wobble) > 0.01;
        expect(differ).toBe(true);
      }
    }
  });
});

// =====================================================================
// 10. Combined extremes: boundary validation
// =====================================================================

describe("sound params -- combined extreme inputs", () => {
  it("max expressivity at day 0 still has low complexity but high volume", () => {
    const params = soundParams("vibration", { energy: 100, mood: 100 }, 0, {
      expressiveness: 100,
      sensitivity: 100,
    });
    expect(params.complexity).toBeCloseTo(0.1, 5);
    expect(params.volume).toBeGreaterThan(0.5);
  });

  it("all 8 sound fields are valid at every combination of species/status/trait extremes", () => {
    const statusExtremes = [
      { mood: 0, energy: 0, comfort: 0 },
      { mood: 100, energy: 100, comfort: 100 },
    ];
    const traitExtremes = [
      { sensitivity: 0, expressiveness: 0 },
      { sensitivity: 100, expressiveness: 100 },
    ];

    for (const species of ALL_SPECIES) {
      for (const status of statusExtremes) {
        for (const traits of traitExtremes) {
          const p = soundParams(species, status, 0, traits);
          expect(p.volume).toBeGreaterThanOrEqual(0);
          expect(p.volume).toBeLessThanOrEqual(1);
          expect(p.wobble).toBeGreaterThanOrEqual(0);
          expect(p.wobble).toBeLessThanOrEqual(1);
          expect(p.patternWeight).toBeGreaterThanOrEqual(0);
          expect(p.patternWeight).toBeLessThanOrEqual(1);
          expect(p.cryWeight).toBeGreaterThanOrEqual(0);
          expect(p.cryWeight).toBeLessThanOrEqual(1);
          expect(p.complexity).toBeGreaterThanOrEqual(0);
          expect(p.complexity).toBeLessThanOrEqual(1);
          expect(p.pitch).toBeGreaterThanOrEqual(80);
          expect(p.pitch).toBeLessThanOrEqual(800);
          expect(p.tempo).toBeGreaterThanOrEqual(30);
          expect(p.tempo).toBeLessThanOrEqual(200);
          expect(["sine", "square", "triangle", "sawtooth"]).toContain(p.waveform);
        }
      }
    }
  });
});
